### ISSUE TITLE
Blog?

### ISSUE THREAD

**Issue by goldfirere** [haskellfoundation/haskellfoundation.github.io#118]
Going through some old meeting minutes, I saw a reference to an HF blog. Great! But I don't see a link from our website. Do we have a blog? If so, let's link to it.

**Comment by myShoggoth** [comment]
I'm working with a graphic designer to get the assets we need for our Medium blog, but it is taking second priority to the updated HF one pager. Once that's done (I think we're making final edits now), that will be next up.

**Comment by goldfirere** [comment]
The blog appears to be live now (https://haskell-foundation.medium.com/), but I still see no link to it from our main website.
