### ISSUE TITLE
Error 404 page mentions GitHub

### ISSUE THREAD

**Issue by goldfirere** [haskellfoundation/haskellfoundation.github.io#135]
I ran into this today (by typing in a URL -- not a broken link):

![Screen Shot 2021-10-13 at 10 50 00 AM](https://user-images.githubusercontent.com/1958003/137157645-11bb9246-1da6-43b9-ac48-300fea3f084a.png)

Mentioning GitHub pages here, etc., isn't as professional as it could be. I don't think this is high priority, though.

**Comment by tomjaguarpaw** [comment]
Perhaps this document explains how to deal with that: https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site
