### ISSUE TITLE
Acknowledge Individual Donors As Sponsors Where Only Corporate Logos Are Currently Shown

### ISSUE THREAD

**Issue by human154** [haskellfoundation/haskellfoundation.github.io#156]
Individual donors are sponsoring the Haskell Foundation but only corporate donors are acknowledged with the display of their logos at the bottom of the H.F. website.  There should be a logo-like acknowledgement that individuals are also sponsoring the H.F.

I've made a logo that indicates the current number of donors (as of 2021-11-15).  I'm willing to update the logo with the new current number of donors (monthly):

![image-to-acknowledge-individual-donors](https://user-images.githubusercontent.com/46430360/141687697-94727400-83f1-4163-b935-f2647949ec5c.png)

Here is how I would like it placed among the logos:
![mock-up-to-show-placement-of-individual-donor-acknowledgement](https://user-images.githubusercontent.com/46430360/141687847-8c31c56e-5f31-40b5-a0bb-5f3f0d489237.png)

I suggest that if this image is clicked on, then it would be equivalent to clicking on the donate button in the upper right corner of the website.

I posted this issue to Haskell Discourse for community review:
https://discourse.haskell.org/t/a-graphic-to-acknowledge-individual-sponsors-along-with-the-corporate-sponsors/3655?u=human154

**Comment by myShoggoth** [comment]
@human154 can you update the image in the PR and we can get this merged?

**Comment by human154** [comment]
sure,  here's an updated image:
![image-to-acknowledge-individual-donorsdonors](https://user-images.githubusercontent.com/46430360/144310947-9d666768-d951-46f3-951a-2f0a259b1275.png)

**Comment by human154** [comment]
I've added the updated graphic to the pull request: https://github.com/haskellfoundation/haskellfoundation.github.io/pull/160
