### ISSUE TITLE
Haskell Logo Broken on PayPal Donate Page

### ISSUE THREAD

**Issue by jturner** [haskellfoundation/haskellfoundation.github.io#161]
The Haskell Logo used on the PayPal Donation page, linked from the Donate button in the header, is broken. This is the image that is linked to: https://haskell.foundation/static/images/logos/hf-logo-100-alpha.png

<img width="873" alt="Screen Shot 2021-11-22 at 10 20 33 PM" src="https://user-images.githubusercontent.com/1825202/142966701-24d4d789-4e5b-4c74-84dd-71c33bb257f7.png">

**Comment by myShoggoth** [comment]
Thank you for pointing this out, I've fixed it in PayPal.
