### ISSUE TITLE
Video on front page unavailable

### ISSUE THREAD

**Issue by ulysses4ever** [haskellfoundation/haskellfoundation.github.io#174]
as of today.

Screen:
![2022-01-06_10-01-1641481705](https://user-images.githubusercontent.com/6832600/148404129-95513d15-d2e8-4213-a703-6ff6e9407c3f.png)

**Comment by tomjaguarpaw** [comment]
Oh dear, I fear you may be suffering from https://github.com/haskellfoundation/haskellfoundation.github.io/issues/70. Our website hasn't looked like that for quite some time. @ulysses4ever, can you please follow the instructions at https://github.com/haskellfoundation/haskellfoundation.github.io/issues/70#issuecomment-899465080 and also report (on https://github.com/haskellfoundation/haskellfoundation.github.io/issues/70) the name of the script that you had to unregister? Thanks.

(I suspect following those instructions will resolve this ticket.)

**Comment by ulysses4ever** [comment]
Oh, indeed, that was it. Thanks a lot and sorry for the noise!

**Comment by tomjaguarpaw** [comment]
It's not noise at all. It's important to try to track down this mysterious failure of cache invalidation caused by the web workers.
