### ISSUE TITLE
Slack link is hard to find

### ISSUE THREAD

**Issue by ulysses4ever** [haskellfoundation/haskellfoundation.github.io#195]
Hello, following up on a Discourse discussion, I’d like to point out that the Slack link is really hard to discover. Apparently, it’s on the Projects page. Would it be possible to add it to the Contacts page? (Or About page, maybe.)

**Comment by ulysses4ever** [comment]
It turns out it's on the contacts page. Sorry for the noise.

**Comment by myShoggoth** [comment]
Appreciate you digging deeper!

**Comment by tomjaguarpaw** [comment]
Yup, thanks for taking the time to suggest UX improvements even if this one turned out to be redundant.
