### ISSUE TITLE
[Deployment] Create a way to deploy the master branch to the live site.

### ISSUE THREAD

**Issue by myShoggoth** [haskellfoundation/haskellfoundation.github.io#28]

**Comment by tomjaguarpaw** [comment]
I want to automatically deploy haskell.org (https://github.com/haskell-infra/www.haskell.org/issues/83). I was thinking of a Github Action which builds the site and sftps it to the server. I was wondering how you do deployments of the master branch to the live site.

**Comment by tomjaguarpaw** [comment]
I've worked out how to do this now: https://github.com/haskell-infra/www.haskell.org/pull/87

**Comment by myShoggoth** [comment]
I did something different for my own website using circleci, I may try to port it to github actions soon. https://github.com/myShoggoth/myShoggoth.github.io/blob/hakyll/.circleci/config.yml

Another option would be to keep things as they are and add a commit rebuilt files after build step, which seems more likely for the HF site.
