### ISSUE TITLE
Please publish the website

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskellfoundation/haskellfoundation.github.io#29]
Unless there are major errors in the redux website I would encourage @myShoggoth and/or @emilypi to publish it as soon as possible.

The current website is severely out of date. Most concerningly it still links to the call for nomination to the Board of Directors (and ED). I think it's a pretty bad look when fundraising to have a website that is outdated in this way.

There may be concerns about minor errors that remain on the redux website. Make opinion is to not worry about them. The quickest way to get minor errors reported and fixed is to publish them!

**Comment by goldfirere** [comment]
I tend to agree here -- would love to get this out the door.

**Comment by tomjaguarpaw** [comment]
[New website](https://haskell.foundation/) published and looks great!
