### ISSUE TITLE
Haskell eXchange video no longer available

### ISSUE THREAD

**Issue by kukimik** [haskellfoundation/haskellfoundation.github.io#375]
The video of Simon Peyton Jones announcing the Haskell Foundation at the Haskell eXchange conference on November 4, 2020 is no longer available. This is on the landing page https://haskell.foundation/ and looks bad:

![image](https://github.com/haskellfoundation/haskellfoundation.github.io/assets/53443372/45fc88a0-b7c8-4a84-9130-517a9a49800d)

**Comment by jmct** [comment]
Thanks for the heads up!

I wonder when it became unavailable, it was up there last time I updated the website... I'll have to see if the video is available via some other means...

**Comment by Bodigrim** [comment]
Skills Matter Youtube channel is gone with all of their intellectual property: https://www.youtube.com/@skills_matter

**Comment by chreekat** [comment]
Their website is also gone, https://skillsmatter.com/conferences/13135-haskell-exchange-2020#program . On LinkedIn they mention some kind of relaunch...

**Comment by jmct** [comment]
I view the current solution (removing it completely) as a temporary fix. Ideally we'll be able to work with folks to get access to that video again.
