### ISSUE TITLE
Repeated heading text in content block

### ISSUE THREAD

**Issue by endgame** [haskellfoundation/haskellfoundation.github.io#39]
> Haskell is not “just another programming language”: it embodies a radical and elegant attack on the entire enterprise of writing software. It profoundly influences the world of software for the better. 

I wouldn't repeat the heading. Suggest:
> Haskell embodies an elegant and radically different approach to the enterprise of writing software. It has and will continue to profoundly influence the world of software for the better.

(Then have two links: "Learn about Haskell" and "how Haskell shaped the industry" (talk about industrial deployment, the FP-everywhere trend, LINQ, etc)

**Comment by emilypi** [comment]
Fixed in a recent PR, thanks @endgame
