### ISSUE TITLE
"We are Underway" - Heading/content mismatch

### ISSUE THREAD

**Issue by endgame** [haskellfoundation/haskellfoundation.github.io#40]
> "we are underway"

I like the header (at least while HF is "new"), but the content doesn't match. Consider putting a recent decision in there (like partnerships or something), or make it a newsbox?

**Comment by emilypi** [comment]
This was fixed in one of the PRs. It now says "We drive change". I think it's useful as a statement. Perhaps in the future we can turn this into a newsbox or something. We'll have to decide.

**Comment by endgame** [comment]
Honestly, I'm not sure anymore.
