### ISSUE TITLE
Drop mailing lists from frontpage, replace with Discourse (?)

### ISSUE THREAD

**Issue by liskin** [haskellfoundation/haskellfoundation.github.io#61]
The home page lists two mailing lists in the "How To Follow HF Developments" section but the last post to both is a message about the retiring of those lists:
* https://mail.haskell.org/pipermail/hf-announce/2021-April/000006.html
* https://mail.haskell.org/pipermail/hf-discuss/2021-April/000024.html

**Comment by liskin** [comment]
Oh, apparently a shift-reload was needed. Sorry for the noise.

Still, there's "or join a mailing list" under the "Follow HF Developments" heading…

**Comment by liskin** [comment]
Actually, the even shift-reload is not enough, the old site keeps coming back. I had to manually stop its service worker in Chrome DevTools. You might want to investigate this before doing a big PR (in the marketing, not git, meaning) launch.

**Comment by Bodigrim** [comment]
Same for me, old site keeps coming back.

**Comment by emilypi** [comment]
Remember to purge your browser caches *and* their workers! That should fix the issue.
