### ISSUE TITLE
404 for sidebar links

### ISSUE THREAD

**Issue by andys8** [haskellfoundation/haskellfoundation.github.io#64]
## Issue

Clicking some of the links will show a 404 error page.

## How to reproduce

* https://haskell.foundation/
* Click "Who we are" in the sidebar
* https://haskell.foundation/en/who-we-are/

![Screenshot_20210519-105455](https://user-images.githubusercontent.com/13085980/118785023-bf58c780-b890-11eb-9bbb-68c1800aabc2.jpg)

https://github.com/haskellfoundation/haskellfoundation.github.io/blob/b69d861999357921704d2ab87837c5cb94574b23/site/templates/nav.html#L15

Is this enough to reproduce the issue or is more information necessary? Thanks

**Comment by emilypi** [comment]
Thanks @andys8 - it is enough information for us to go on - thank you!

**Comment by gelisam** [comment]
"Who we are" now works fine for me, but it is now the "FAQ" link which is broken. Clicking on the link does nothing, while opening it in a new tab opens https://haskell.foundation/en/faq/, which is a blank page instead of a 404. The correct URL seems to be https://haskell.foundation/faq/

**Comment by ulysses4ever** [comment]
@gelisam the FAQ link seems to work fine now either. 

Everyone, should we close it?

**Comment by andys8** [comment]
Seems to be resolved. Interestingly I still see the old page / design with dead links in the Samsung mobile Browser due to caching. Same device and chrome shows a completely different page. Normal refresh (what users would do) doesn't change it.

Only in parts relevant for this issue, but I did want to write it down since agressive caching could lead to issues like this.

**Comment by ulysses4ever** [comment]
Thanks for the feedback, @andys8! I think that would be #70. So I still think we should close this one. But admins would know better.

**Comment by gelisam** [comment]
> @gelisam the FAQ link seems to work fine now either.

I confirm that all the links now work for me on Chrome for macOS, and after [clearing the cache](https://android.stackexchange.com/questions/188189/clear-cache-for-specific-site-on-chrome-for-android), they also work on Chrome for Android.
