### ISSUE TITLE
Unnecessary newlines in list bullets on vision page

### ISSUE THREAD

**Issue by snoyberg** [haskellfoundation/haskellfoundation.github.io#84]
A picture's worth a thousand words:

![image](https://user-images.githubusercontent.com/49415/124160897-69895900-daa5-11eb-879a-44fca834f169.png)

For example, "Open source" should line up with the bullet above it.

**Comment by myShoggoth** [comment]
I believe we fixed this a few weeks ago but forgot to close the issue. I checked it on Brave, Edge, Firefox, and Chrome.
