### ISSUE TITLE
HF address on website

### ISSUE THREAD

**Issue by goldfirere** [haskellfoundation/haskellfoundation.github.io#88]
We have a real postal address now. Let's publish it in our footer. This will communicate that we really exist in 3-d space.

**Comment by elland** [comment]
@goldfirer if you send me the address I can open a PR. 👍

**Comment by goldfirere** [comment]
```
Haskell Foundation, Inc.
2093 Philadelphia Pike #8119
Claymont, DE 19703 
USA
```

**Comment by elland** [comment]
@goldfirere Thoughts?

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/54423/126558294-40ee1be0-f71c-4114-898d-85550a1b26b5.png">

**Comment by goldfirere** [comment]
Personally, I would left-align the lines of the address, but that probably means you should do something else -- history suggests that most of my visual design ideas are more like anti-ideas.

**Comment by elland** [comment]
@goldfirere I'm inclined to agree (with left-aligning), but my design ideas are usually also quite wrong, so now I'm unsure how to proceed. 

I'll see how it looks left-aligned in any case at least for comparison's sake.

**Comment by elland** [comment]
Better alignment. More contrast.

![image](https://user-images.githubusercontent.com/54423/126649954-dda46772-7617-4020-a36c-d1118f5e5f4d.png)

**Comment by myShoggoth** [comment]
I think that looks good, although I'd reduce the font of the address
section (the likelihood of anyone needing it is very low).

**Comment by elland** [comment]
@myShoggoth good point. How about now?

![image](https://user-images.githubusercontent.com/54423/126695658-42aee8cd-f9d3-4b60-9ffe-008e04ade44f.png)

**Comment by myShoggoth** [comment]
Perfect!

**Comment by elland** [comment]
@myShoggoth Alright. Code is up on #94.

**Comment by myShoggoth** [comment]
#94 is merged, thank you @elland !
