### ISSUE TITLE
Two logos?

### ISSUE THREAD

**Issue by goldfirere** [haskellfoundation/haskellfoundation.github.io#90]
The website features a logo in the header (the Haskell logo redesigned to feature an F) and a logo in the footer (the Haskell logo followed by a separate F). Is it intentional to have two similar-but-different logos? I think I'd prefer one (the one in the header), used consistently.

**Comment by elland** [comment]
Related to #47.

@emilypi seems to like it :sweat_smile:

**Comment by myShoggoth** [comment]
I'm going to close this as a duplicate of #47 and work on that today.
