### ISSUE TITLE
Make RSS feed more easily discoverable.

### ISSUE THREAD

**Issue by ffaf1** [haskellfoundation/haskellfoundation.github.io#96]
Problem: RSS feed could be more easily discoverable ([see this message](https://discourse.haskell.org/t/the-haskell-interlude-podcast-teaser/2773/7)).

Proposed solution: add a simple `RSS podcast feed` in the podcast page.

**Comment by myShoggoth** [comment]
Looks like this will be addressed by https://github.com/haskellfoundation/haskellfoundation.github.io/pull/103
